import { KeyPurpose, SignatureScheme, StackrConfig } from "@stackr/sdk";
import dotenv from "dotenv";

dotenv.config();

// this file is generated by the deployment script
import * as deployment from "./deployment.json";
const REGISTRY_CONTRACT = "0x023a686aeAe5394256112e647Fc6cE5e57F9d687";

const stackrConfig: StackrConfig = {
  stackrApp: {
    appId: deployment.app_id,
    appInbox: deployment.app_inbox,
  },
  sequencer: {
    batchSize: 16,
    batchTime: 1000,
  },
  syncer: {
    slotTime: 1000,
    vulcanRPC: "http://3.6.115.65",
    L1RPC: "http://3.6.115.65:8545",
  },
  operator: {
    accounts: [
      {
        privateKey: process.env.PRIVATE_KEY as string,
        purpose: KeyPurpose.BATCH,
        scheme: SignatureScheme.ECDSA,
      },
    ],
  },
  domain: {
    name: "Stackr MVP v0",
    version: "1",
    chainId: deployment.app_id,
    verifyingContract: deployment.app_inbox,
    salt: "0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
  },
  datastore: {
    uri: "./erc20.sqlite",
  },
  registryContract: REGISTRY_CONTRACT,
  logLevel: "log",
};

export { stackrConfig };
