import type { Metadata } from "next";
import "./globals.css";

import local from "next/font/local";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import Provider from "@/components/provider";
import { Toaster } from "@/components/ui/sonner";

const basier = local({
  src: [
    {
      path: "../../public/fonts/BasierSquare-Regular.otf",
      weight: "800",
    },
  ],
  variable: "--font-basier",
});

export const metadata: Metadata = {
  title: "Intents-MRU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(basier.className, "max-w-7xl mx-auto")}>
        <Provider>
          <Navbar />
          <div>{children}</div>
        </Provider>
        <Toaster richColors />
      </body>
    </html>
  );
}
